# Database connection properties
connection.url=jdbc:mysql://localhost:3308/openmrs?autoReconnect=true&sessionVariables=default_storage_engine%3DInnoDB&useUnicode=true&characterEncoding=UTF-8
connection.username=root
connection.password=Admin123

# Other properties
auto_update_database=true
module.allow_web_admin=true
junit.username=admin
junit.password=test